import Nav from "@/src/components/Nav";
import "../../styles/index.scss";
import type { Metadata } from "next";
import Profile from "@/src/components/Profile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Nav />
      <main>
        <Profile title="Ayobami Adedapo" claims={54} wishes={200} />
        <div className="dsb-main-cnt">{children}</div>
      </main>
    </>
  );
}
